[2023-07-03 03:58:45,882][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 03:58:45,932][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
                                             ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data//predict'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 40, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'torchvision.datasets.folder.ImageFolder':
FileNotFoundError(2, 'No such file or directory')
full_key: data.predict_dataset
[2023-07-03 03:58:45,935][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-03_03-58-45
[2023-07-03 04:03:07,685][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 04:03:07,731][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
                                             ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data//test'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 40, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'torchvision.datasets.folder.ImageFolder':
FileNotFoundError(2, 'No such file or directory')
full_key: data.predict_dataset
[2023-07-03 04:03:07,734][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-03_04-03-07
[2023-07-03 04:07:07,352][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 04:07:07,467][classifier.train][INFO] - Instantiating model <dl_pkg.models.vit_module.VitLitModule>
[2023-07-03 04:07:07,470][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/utils.py", line 635, in _locate
    obj = import_module(part0)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.11.1/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'dl_pkg'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/utils.py", line 637, in _locate
    raise ImportError(
ImportError: Error loading 'dl_pkg.models.vit_module.VitLitModule':
ModuleNotFoundError("No module named 'dl_pkg'")
Are you sure that module 'dl_pkg' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 43, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'dl_pkg.models.vit_module.VitLitModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
[2023-07-03 04:07:07,472][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-03_04-07-07
[2023-07-03 04:10:05,892][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 04:10:06,027][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-03 04:10:06,044][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: VitLitModule.__init__() got an unexpected keyword argument 'topk'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 43, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'classifier.models.vit_module.VitLitModule':
TypeError("VitLitModule.__init__() got an unexpected keyword argument 'topk'")
full_key: model
[2023-07-03 04:10:06,047][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-03_04-10-05
[2023-07-03 04:16:38,018][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 04:16:38,164][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-03 04:16:38,184][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: VitLitModule.__init__() got an unexpected keyword argument 'net'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 43, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'classifier.models.vit_module.VitLitModule':
TypeError("VitLitModule.__init__() got an unexpected keyword argument 'net'")
full_key: model
[2023-07-03 04:16:38,186][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-03_04-16-37
[2023-07-03 04:17:19,155][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 04:17:19,275][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-03 04:17:19,307][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-03 04:17:19,391][classifier.train][INFO] - Starting training!
[2023-07-03 04:18:35,438][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 57, in train
    trainer.fit(model=model, datamodule=datamodule,
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 531, in fit
    call._call_and_handle_interrupt(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 570, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 975, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1018, in _run_stage
    self.fit_loop.run()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 189, in advance
    batch = next(data_fetcher)
            ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 136, in __next__
    self._fetch_next_batch(self.dataloader_iter)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 150, in _fetch_next_batch
    batch = next(iterator)
            ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 284, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 65, in __next__
    out[i] = next(self.iterators[i])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1345, in _next_data
    return self._process_data(data)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 1371, in _process_data
    data.reraise()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/_utils.py", line 644, in reraise
    raise exception
PIL.UnidentifiedImageError: Caught UnidentifiedImageError in DataLoader worker process 14.
Original Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/_utils/worker.py", line 308, in _worker_loop
    data = fetcher.fetch(index)
           ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 229, in __getitem__
    sample = self.loader(path)
             ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 268, in default_loader
    return pil_loader(path)
           ^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 247, in pil_loader
    img = Image.open(f)
          ^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='./data//PetImages_split/train/Cat/666.jpg'>

[2023-07-03 04:18:35,443][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-03_04-17-19
[2023-07-03 04:33:37,247][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 04:33:37,359][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-03 04:33:37,393][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-03 04:33:37,481][classifier.train][INFO] - Starting training!
[2023-07-03 04:35:15,514][classifier.train][INFO] - Starting testing!
[2023-07-03 04:35:15,514][classifier.train][WARNING] - Best ckpt not found! Using current weights for testing...
[2023-07-03 04:35:29,236][classifier.train][INFO] - Best ckpt path: None
[2023-07-03 04:35:29,238][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-03_04-33-37
[2023-07-03 04:35:29,238][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-07-03 04:38:11,474][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 04:38:11,586][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-03 04:38:11,619][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-03 04:38:11,703][classifier.train][INFO] - Starting training!
[2023-07-03 04:39:58,617][classifier.train][INFO] - Starting testing!
[2023-07-03 04:39:58,618][classifier.train][WARNING] - Best ckpt not found! Using current weights for testing...
[2023-07-03 04:40:11,830][classifier.train][INFO] - Best ckpt path: None
[2023-07-03 04:40:11,831][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-03_04-38-11
[2023-07-03 04:40:11,832][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-07-03 05:54:32,681][__main__][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-03 05:54:32,800][__main__][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-03 05:54:32,870][__main__][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-03 05:54:32,956][__main__][INFO] - Starting training!
[2023-07-03 05:59:13,442][__main__][INFO] - Starting testing!
[2023-07-03 05:59:13,442][__main__][WARNING] - Best ckpt not found! Using current weights for testing...
[2023-07-03 05:59:24,418][__main__][INFO] - Best ckpt path: None
[2023-07-03 05:59:24,419][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-03_05-54-32
[2023-07-03 05:59:24,419][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-07-22 17:10:24,620][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-22 17:10:24,720][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-22 17:10:24,758][classifier.train][INFO] - Instantiating loggers...
[2023-07-22 17:10:24,758][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-07-22 17:10:24,761][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-07-22 17:10:25,172][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-07-22 17:10:25,174][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-07-22 17:10:25,175][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-22 17:10:25,458][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-07-22 17:10:25,458][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-07-22 17:10:25,458][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-07-22 17:10:25,459][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-07-22 17:10:25,459][classifier.train][INFO] - Starting training!
[2023-07-22 17:10:25,639][aim.sdk.reporter][INFO] - creating RunStatusReporter for 65b984fe0d4e40cebe7620db
[2023-07-22 17:10:25,639][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 17:10:25,640][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7fc07e169490>
[2023-07-22 17:12:25,473][pytorch_lightning.utilities.rank_zero][INFO] - `Trainer.fit` stopped: `max_epochs=1` reached.
[2023-07-22 17:12:25,731][classifier.train][INFO] - Starting testing!
[2023-07-22 17:12:25,731][classifier.train][WARNING] - Best ckpt not found! Using current weights for testing...
[2023-07-22 17:12:25,762][aim.sdk.reporter][INFO] - creating RunStatusReporter for 65b984fe0d4e40cebe7620db
[2023-07-22 17:12:25,762][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 17:12:25,762][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7fc07e9a9b10>
[2023-07-22 17:12:41,138][classifier.train][INFO] - Best ckpt path: None
[2023-07-22 17:12:41,140][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_17-10-24
[2023-07-22 17:12:41,141][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-07-22 17:22:39,391][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-22 17:22:39,487][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-22 17:22:39,519][classifier.train][INFO] - Instantiating loggers...
[2023-07-22 17:22:39,519][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-07-22 17:22:39,522][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-07-22 17:22:40,234][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-07-22 17:22:40,236][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-07-22 17:22:40,238][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-22 17:22:40,332][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-07-22 17:22:40,333][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-07-22 17:22:40,333][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-07-22 17:22:40,333][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-07-22 17:22:40,333][classifier.train][INFO] - Starting training!
[2023-07-22 17:22:40,559][aim.sdk.reporter][INFO] - creating RunStatusReporter for 57e195e030eb48feb453ba1f
[2023-07-22 17:22:40,559][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 17:22:40,560][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7f5f9ebd7e50>
[2023-07-22 17:34:42,588][pytorch_lightning.utilities.rank_zero][INFO] - `Trainer.fit` stopped: `max_epochs=5` reached.
[2023-07-22 17:34:42,951][classifier.train][INFO] - Starting testing!
[2023-07-22 17:34:42,952][classifier.train][WARNING] - Best ckpt not found! Using current weights for testing...
[2023-07-22 17:34:42,987][aim.sdk.reporter][INFO] - creating RunStatusReporter for 57e195e030eb48feb453ba1f
[2023-07-22 17:34:42,988][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 17:34:42,988][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7f5f9ebdf350>
[2023-07-22 17:34:57,916][classifier.train][INFO] - Best ckpt path: None
[2023-07-22 17:34:57,918][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_17-22-39
[2023-07-22 17:34:57,918][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-07-22 18:57:07,184][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-22 18:57:07,276][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-22 18:57:07,335][classifier.train][INFO] - Instantiating loggers...
[2023-07-22 18:57:07,336][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-07-22 18:57:07,339][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-07-22 18:57:07,802][aim.utils.tracking][WARNING] - --------------------------------------------------------------------------
[2023-07-22 18:57:07,802][aim.utils.tracking][WARNING] -                  Aim collects anonymous usage analytics.                 
[2023-07-22 18:57:07,802][aim.utils.tracking][WARNING] -                         Read how to opt-out here:                         
[2023-07-22 18:57:07,802][aim.utils.tracking][WARNING] -     https://aimstack.readthedocs.io/en/latest/community/telemetry.html    
[2023-07-22 18:57:07,802][aim.utils.tracking][WARNING] - --------------------------------------------------------------------------
[2023-07-22 18:57:08,038][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-07-22 18:57:08,040][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-07-22 18:57:08,043][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-22 18:57:08,309][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-07-22 18:57:08,310][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-07-22 18:57:08,310][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-07-22 18:57:08,310][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-07-22 18:57:08,310][classifier.train][INFO] - Starting training!
[2023-07-22 18:57:08,511][aim.sdk.reporter][INFO] - creating RunStatusReporter for 0e531267381a472d99c08f3b
[2023-07-22 18:57:08,511][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 18:57:08,511][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7f7b84548690>
[2023-07-22 19:18:16,018][pytorch_lightning.utilities.rank_zero][INFO] - `Trainer.fit` stopped: `max_epochs=10` reached.
[2023-07-22 19:18:16,451][classifier.train][INFO] - Starting testing!
[2023-07-22 19:18:16,451][classifier.train][WARNING] - Best ckpt not found! Using current weights for testing...
[2023-07-22 19:18:16,482][aim.sdk.reporter][INFO] - creating RunStatusReporter for 0e531267381a472d99c08f3b
[2023-07-22 19:18:16,482][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 19:18:16,482][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7f7b74b57bd0>
[2023-07-22 19:18:41,036][classifier.train][INFO] - Best ckpt path: None
[2023-07-22 19:18:41,039][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_18-57-07
[2023-07-22 19:18:41,040][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-07-22 19:48:18,496][classifier.train][INFO] - Instantiating datamodule <ninja.datamodule.mnist_datamodule.MNISTDataModule>
[2023-07-22 19:48:18,497][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/utils.py", line 635, in _locate
    obj = import_module(part0)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.11.1/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ninja'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/utils.py", line 637, in _locate
    raise ImportError(
ImportError: Error loading 'ninja.datamodule.mnist_datamodule.MNISTDataModule':
ModuleNotFoundError("No module named 'ninja'")
Are you sure that module 'ninja' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 43, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'ninja.datamodule.mnist_datamodule.MNISTDataModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: data
[2023-07-22 19:48:18,500][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-48-18
[2023-07-22 19:51:05,251][classifier.train][INFO] - Instantiating datamodule <classifier.data.mnist_datamodule.MNISTDataModule>
[2023-07-22 19:51:05,257][classifier.train][INFO] - Instantiating model <ninja.models.mnist_module.MNISTLitModule>
[2023-07-22 19:51:05,258][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/utils.py", line 635, in _locate
    obj = import_module(part0)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.11.1/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ninja'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/utils.py", line 637, in _locate
    raise ImportError(
ImportError: Error loading 'ninja.models.mnist_module.MNISTLitModule':
ModuleNotFoundError("No module named 'ninja'")
Are you sure that module 'ninja' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 46, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'ninja.models.mnist_module.MNISTLitModule', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model
[2023-07-22 19:51:05,261][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-51-05
[2023-07-22 19:51:41,355][classifier.train][INFO] - Instantiating datamodule <classifier.data.mnist_datamodule.MNISTDataModule>
[2023-07-22 19:51:41,357][classifier.train][INFO] - Instantiating model <classifier.models.mnist_module.MNISTLitModule>
[2023-07-22 19:51:41,361][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/utils.py", line 635, in _locate
    obj = import_module(part0)
          ^^^^^^^^^^^^^^^^^^^^
  File "/home/gitpod/.pyenv/versions/3.11.1/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1206, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1178, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1142, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'ninja'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 134, in _resolve_target
    target = _locate(target)
             ^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/utils.py", line 637, in _locate
    raise ImportError(
ImportError: Error loading 'ninja.models.components.simple_dense_net.SimpleDenseNet':
ModuleNotFoundError("No module named 'ninja'")
Are you sure that module 'ninja' is installed?

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 46, in train
    model: LightningModule = hydra.utils.instantiate(cfg.model)
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 333, in instantiate_node
    _target_ = _resolve_target(node.get(_Keys.TARGET), full_key)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 139, in _resolve_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error locating target 'ninja.models.components.simple_dense_net.SimpleDenseNet', set env var HYDRA_FULL_ERROR=1 to see chained exception.
full_key: model.net
[2023-07-22 19:51:41,364][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-51-41
[2023-07-22 19:53:47,562][classifier.train][INFO] - Instantiating datamodule <classifier.data.mnist_datamodule.MNISTDataModule>
[2023-07-22 19:53:47,565][classifier.train][INFO] - Instantiating model <classifier.models.mnist_module.MNISTLitModule>
[2023-07-22 19:53:47,573][classifier.train][INFO] - Instantiating loggers...
[2023-07-22 19:53:47,574][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-07-22 19:53:47,577][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-07-22 19:53:47,960][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-07-22 19:53:47,963][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-07-22 19:53:47,964][classifier.train][INFO] - Instantiating callbacks...
[2023-07-22 19:53:47,965][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2023-07-22 19:53:47,967][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2023-07-22 19:53:47,967][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2023-07-22 19:53:47,968][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-22 19:53:48,238][pytorch_lightning.utilities.rank_zero][INFO] - Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
[2023-07-22 19:53:48,257][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-07-22 19:53:48,257][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-07-22 19:53:48,257][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-07-22 19:53:48,257][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-07-22 19:53:48,258][classifier.train][INFO] - Logging hyperparameters!
[2023-07-22 19:53:48,258][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 68, in train
    utils.log_hyperparameters(object_dict)
    ^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: module 'classifier.utils' has no attribute 'log_hyperparameters'
[2023-07-22 19:53:48,259][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-53-47
[2023-07-22 19:57:23,821][classifier.train][INFO] - Instantiating datamodule <classifier.data.mnist_datamodule.MNISTDataModule>
[2023-07-22 19:57:23,824][classifier.train][INFO] - Instantiating model <classifier.models.mnist_module.MNISTLitModule>
[2023-07-22 19:57:23,832][classifier.train][INFO] - Instantiating loggers...
[2023-07-22 19:57:23,833][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-07-22 19:57:23,835][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-07-22 19:57:24,216][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-07-22 19:57:24,219][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-07-22 19:57:24,221][classifier.train][INFO] - Instantiating callbacks...
[2023-07-22 19:57:24,221][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2023-07-22 19:57:24,224][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2023-07-22 19:57:24,224][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2023-07-22 19:57:24,225][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-22 19:57:24,498][pytorch_lightning.utilities.rank_zero][INFO] - Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
[2023-07-22 19:57:24,520][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-07-22 19:57:24,521][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-07-22 19:57:24,521][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-07-22 19:57:24,521][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-07-22 19:57:24,521][classifier.train][INFO] - Logging hyperparameters!
[2023-07-22 19:57:24,525][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 68, in train
    utils.log_hyperparameters(object_dict)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning_utilities/core/rank_zero.py", line 32, in wrapped_fn
    return fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/logging_utils.py", line 37, in log_hyperparameters
    hparams["data"] = cfg["datamodule"]
                      ~~~^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 371, in __getitem__
    self._format_and_raise(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/_utils.py", line 819, in format_and_raise
    _raise(ex, cause)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 369, in __getitem__
    return self._get_impl(key=key, default_value=_DEFAULT_MARKER_)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 442, in _get_impl
    node = self._get_child(
           ^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/basecontainer.py", line 73, in _get_child
    child = self._get_node(
            ^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 475, in _get_node
    self._validate_get(key)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/dictconfig.py", line 164, in _validate_get
    self._format_and_raise(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/base.py", line 231, in _format_and_raise
    format_and_raise(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/_utils.py", line 899, in format_and_raise
    _raise(ex, cause)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/omegaconf/_utils.py", line 797, in _raise
    raise ex.with_traceback(sys.exc_info()[2])  # set env var OC_CAUSE=1 for full trace
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
omegaconf.errors.ConfigKeyError: Key 'datamodule' is not in struct
    full_key: datamodule
    object_type=dict
[2023-07-22 19:57:24,533][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-57-23
[2023-07-22 19:58:10,859][classifier.train][INFO] - Instantiating datamodule <classifier.data.mnist_datamodule.MNISTDataModule>
[2023-07-22 19:58:10,862][classifier.train][INFO] - Instantiating model <classifier.models.mnist_module.MNISTLitModule>
[2023-07-22 19:58:10,870][classifier.train][INFO] - Instantiating loggers...
[2023-07-22 19:58:10,871][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-07-22 19:58:10,873][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-07-22 19:58:11,224][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-07-22 19:58:11,227][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-07-22 19:58:11,229][classifier.train][INFO] - Instantiating callbacks...
[2023-07-22 19:58:11,229][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2023-07-22 19:58:11,231][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2023-07-22 19:58:11,232][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2023-07-22 19:58:11,233][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-22 19:58:11,476][pytorch_lightning.utilities.rank_zero][INFO] - Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
[2023-07-22 19:58:11,495][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-07-22 19:58:11,495][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-07-22 19:58:11,495][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-07-22 19:58:11,495][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-07-22 19:58:11,495][classifier.train][INFO] - Logging hyperparameters!
[2023-07-22 19:58:11,521][aim.sdk.reporter][INFO] - creating RunStatusReporter for 0d21a13f406e4f4ab978d8a9
[2023-07-22 19:58:11,521][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 19:58:11,522][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7f1b56e71850>
[2023-07-22 19:58:11,681][classifier.train][INFO] - Starting training!
[2023-07-22 19:58:39,692][pytorch_lightning.utilities.rank_zero][INFO] - `Trainer.fit` stopped: `max_epochs=2` reached.
[2023-07-22 19:58:39,946][classifier.train][INFO] - Starting testing!
[2023-07-22 19:58:40,020][aim.sdk.reporter][INFO] - creating RunStatusReporter for 0d21a13f406e4f4ab978d8a9
[2023-07-22 19:58:40,020][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 19:58:40,020][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7f1b56ec6410>
[2023-07-22 19:58:40,044][pytorch_lightning.utilities.rank_zero][INFO] - Restoring states from the checkpoint path at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 19:58:40,068][pytorch_lightning.utilities.rank_zero][INFO] - Loaded model weights from the checkpoint at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 19:58:44,445][classifier.train][INFO] - Best ckpt path: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 19:58:44,446][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10
[2023-07-22 19:58:44,447][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-07-22 20:13:19,379][classifier.train][INFO] - Instantiating datamodule <classifier.data.mnist_datamodule.MNISTDataModule>
[2023-07-22 20:13:19,382][classifier.train][INFO] - Instantiating model <classifier.models.mnist_module.MNISTLitModule>
[2023-07-22 20:13:19,389][classifier.train][INFO] - Instantiating loggers...
[2023-07-22 20:13:19,390][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-07-22 20:13:19,392][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-07-22 20:13:19,776][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-07-22 20:13:19,779][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-07-22 20:13:19,781][classifier.train][INFO] - Instantiating callbacks...
[2023-07-22 20:13:19,781][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2023-07-22 20:13:19,784][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2023-07-22 20:13:19,784][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2023-07-22 20:13:19,785][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-22 20:13:20,061][pytorch_lightning.utilities.rank_zero][INFO] - Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
[2023-07-22 20:13:20,082][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-07-22 20:13:20,083][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-07-22 20:13:20,083][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-07-22 20:13:20,083][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-07-22 20:13:20,083][classifier.train][INFO] - Logging hyperparameters!
[2023-07-22 20:13:20,108][aim.sdk.reporter][INFO] - creating RunStatusReporter for c7e9dbb2ad034b1a8fc151bb
[2023-07-22 20:13:20,109][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 20:13:20,109][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7fa06a5b1450>
[2023-07-22 20:13:20,280][classifier.train][INFO] - Starting training!
[2023-07-22 20:13:20,549][pytorch_lightning.utilities.rank_zero][INFO] - Restoring states from the checkpoint path at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 20:13:20,600][pytorch_lightning.utilities.rank_zero][INFO] - Restored all states from the checkpoint at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 20:13:25,332][pytorch_lightning.utilities.rank_zero][INFO] - `Trainer.fit` stopped: `max_epochs=2` reached.
[2023-07-22 20:13:25,449][classifier.train][INFO] - Starting testing!
[2023-07-22 20:13:25,519][aim.sdk.reporter][INFO] - creating RunStatusReporter for c7e9dbb2ad034b1a8fc151bb
[2023-07-22 20:13:25,520][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 20:13:25,520][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7fa063eeb7d0>
[2023-07-22 20:13:25,544][pytorch_lightning.utilities.rank_zero][INFO] - Restoring states from the checkpoint path at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 20:13:25,572][pytorch_lightning.utilities.rank_zero][INFO] - Loaded model weights from the checkpoint at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 20:13:29,660][classifier.train][INFO] - Best ckpt path: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 20:13:29,661][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_20-13-19
[2023-07-22 20:13:29,662][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-07-22 20:15:08,127][classifier.train][INFO] - Instantiating datamodule <classifier.data.mnist_datamodule.MNISTDataModule>
[2023-07-22 20:15:08,130][classifier.train][INFO] - Instantiating model <classifier.models.mnist_module.MNISTLitModule>
[2023-07-22 20:15:08,137][classifier.train][INFO] - Instantiating loggers...
[2023-07-22 20:15:08,137][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-07-22 20:15:08,140][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-07-22 20:15:08,513][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-07-22 20:15:08,516][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-07-22 20:15:08,518][classifier.train][INFO] - Instantiating callbacks...
[2023-07-22 20:15:08,519][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2023-07-22 20:15:08,521][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2023-07-22 20:15:08,522][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2023-07-22 20:15:08,522][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-07-22 20:15:08,805][pytorch_lightning.utilities.rank_zero][INFO] - Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
[2023-07-22 20:15:08,826][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-07-22 20:15:08,826][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-07-22 20:15:08,826][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-07-22 20:15:08,826][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-07-22 20:15:08,827][classifier.train][INFO] - Logging hyperparameters!
[2023-07-22 20:15:08,854][aim.sdk.reporter][INFO] - creating RunStatusReporter for 2f40cc6b50484c2c9eb29007
[2023-07-22 20:15:08,855][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 20:15:08,855][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7f51a97b8a50>
[2023-07-22 20:15:09,034][classifier.train][INFO] - Starting training!
[2023-07-22 20:15:09,320][pytorch_lightning.utilities.rank_zero][INFO] - Restoring states from the checkpoint path at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 20:15:09,442][pytorch_lightning.utilities.rank_zero][INFO] - Restored all states from the checkpoint at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_19-58-10/checkpoints/epoch_001.ckpt
[2023-07-22 20:16:12,568][pytorch_lightning.utilities.rank_zero][INFO] - `Trainer.fit` stopped: `max_epochs=5` reached.
[2023-07-22 20:16:13,039][classifier.train][INFO] - Starting testing!
[2023-07-22 20:16:13,142][aim.sdk.reporter][INFO] - creating RunStatusReporter for 2f40cc6b50484c2c9eb29007
[2023-07-22 20:16:13,142][aim.sdk.reporter][INFO] - starting from: {}
[2023-07-22 20:16:13,143][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7f51a9335f90>
[2023-07-22 20:16:13,167][pytorch_lightning.utilities.rank_zero][INFO] - Restoring states from the checkpoint path at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_20-15-08/checkpoints/epoch_004.ckpt
[2023-07-22 20:16:13,214][pytorch_lightning.utilities.rank_zero][INFO] - Loaded model weights from the checkpoint at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_20-15-08/checkpoints/epoch_004.ckpt
[2023-07-22 20:16:19,753][classifier.train][INFO] - Best ckpt path: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_20-15-08/checkpoints/epoch_004.ckpt
[2023-07-22 20:16:19,754][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-07-22_20-15-08
[2023-07-22 20:16:19,755][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-08-04 20:03:35,125][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-08-04 20:03:35,243][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-08-04 20:03:35,281][classifier.train][INFO] - Instantiating loggers...
[2023-08-04 20:03:35,297][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-08-04 20:03:35,300][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-08-04 20:03:35,826][aim.utils.tracking][WARNING] - --------------------------------------------------------------------------
[2023-08-04 20:03:35,826][aim.utils.tracking][WARNING] -                  Aim collects anonymous usage analytics.                 
[2023-08-04 20:03:35,826][aim.utils.tracking][WARNING] -                         Read how to opt-out here:                         
[2023-08-04 20:03:35,826][aim.utils.tracking][WARNING] -     https://aimstack.readthedocs.io/en/latest/community/telemetry.html    
[2023-08-04 20:03:35,826][aim.utils.tracking][WARNING] - --------------------------------------------------------------------------
[2023-08-04 20:03:36,005][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-08-04 20:03:36,006][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loggers/mlflow.py", line 151, in __init__
    raise ModuleNotFoundError(str(_MLFLOW_AVAILABLE))
ModuleNotFoundError: False

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 49, in train
    logger: List[Logger] = utils.instantiate_loggers(cfg.get("logger"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/instantiators.py", line 48, in instantiate_loggers
    logger.append(hydra.utils.instantiate(lg_conf))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'lightning.pytorch.loggers.mlflow.MLFlowLogger':
ModuleNotFoundError('False')
full_key: logger.mlflow
[2023-08-04 20:03:36,008][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-08-04_20-03-35
[2023-08-04 20:04:43,054][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-08-04 20:04:43,158][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-08-04 20:04:43,204][classifier.train][INFO] - Instantiating loggers...
[2023-08-04 20:04:43,204][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-08-04 20:04:43,208][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-08-04 20:04:44,022][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-08-04 20:04:44,026][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-08-04 20:04:44,028][classifier.train][INFO] - Instantiating callbacks...
[2023-08-04 20:04:44,028][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2023-08-04 20:04:44,031][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2023-08-04 20:04:44,032][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2023-08-04 20:04:44,033][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-08-04 20:04:44,164][pytorch_lightning.utilities.rank_zero][INFO] - Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
[2023-08-04 20:04:44,187][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-08-04 20:04:44,187][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-08-04 20:04:44,187][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-08-04 20:04:44,188][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-08-04 20:04:44,188][classifier.train][INFO] - Logging hyperparameters!
[2023-08-04 20:04:44,235][aim.sdk.reporter][INFO] - creating RunStatusReporter for 6fd92617f2d14176b69788f9
[2023-08-04 20:04:44,236][aim.sdk.reporter][INFO] - starting from: {}
[2023-08-04 20:04:44,236][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7feb1db17410>
[2023-08-04 20:04:44,453][classifier.train][INFO] - Starting training!
[2023-08-04 20:09:18,070][pytorch_lightning.utilities.rank_zero][INFO] - `Trainer.fit` stopped: `max_epochs=2` reached.
[2023-08-04 20:09:18,166][classifier.train][INFO] - Starting testing!
[2023-08-04 20:09:18,197][aim.sdk.reporter][INFO] - creating RunStatusReporter for 6fd92617f2d14176b69788f9
[2023-08-04 20:09:18,198][aim.sdk.reporter][INFO] - starting from: {}
[2023-08-04 20:09:18,198][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7feb1bf249d0>
[2023-08-04 20:09:18,221][pytorch_lightning.utilities.rank_zero][INFO] - Restoring states from the checkpoint path at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-08-04_20-04-42/checkpoints/epoch_001.ckpt
[2023-08-04 20:09:18,362][pytorch_lightning.utilities.rank_zero][INFO] - Loaded model weights from the checkpoint at /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-08-04_20-04-42/checkpoints/epoch_001.ckpt
[2023-08-04 20:09:31,271][classifier.train][INFO] - Best ckpt path: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-08-04_20-04-42/checkpoints/epoch_001.ckpt
[2023-08-04 20:09:31,272][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-08-04_20-04-42
[2023-08-04 20:09:31,273][classifier.utils.utils][INFO] - Metric name is None! Skipping metric value retrieval...
[2023-08-05 07:01:19,505][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-08-05 07:01:19,509][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 309, in __init__
    super().__init__(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 144, in __init__
    classes, class_to_idx = self.find_classes(self.root)
                            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 218, in find_classes
    return find_classes(directory)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 40, in find_classes
    classes = sorted(entry.name for entry in os.scandir(directory) if entry.is_dir())
                                             ^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: './data//PetImages_split/train'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 43, in train
    datamodule: LightningDataModule = hydra.utils.instantiate(cfg.data)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 342, in instantiate_node
    value = instantiate_node(
            ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'torchvision.datasets.folder.ImageFolder':
FileNotFoundError(2, 'No such file or directory')
full_key: data.train_dataset
[2023-08-05 07:01:19,511][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-08-05_07-01-19
[2023-08-05 07:45:15,250][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-08-05 07:45:15,354][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-08-05 07:45:15,447][classifier.train][INFO] - Instantiating loggers...
[2023-08-05 07:45:15,447][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-08-05 07:45:15,450][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-08-05 07:45:16,080][aim.utils.tracking][WARNING] - --------------------------------------------------------------------------
[2023-08-05 07:45:16,081][aim.utils.tracking][WARNING] -                  Aim collects anonymous usage analytics.                 
[2023-08-05 07:45:16,081][aim.utils.tracking][WARNING] -                         Read how to opt-out here:                         
[2023-08-05 07:45:16,081][aim.utils.tracking][WARNING] -     https://aimstack.readthedocs.io/en/latest/community/telemetry.html    
[2023-08-05 07:45:16,081][aim.utils.tracking][WARNING] - --------------------------------------------------------------------------
[2023-08-05 07:45:16,650][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.MLFlowLogger>
[2023-08-05 07:45:16,654][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.tensorboard.TensorBoardLogger>
[2023-08-05 07:45:16,656][classifier.train][INFO] - Instantiating callbacks...
[2023-08-05 07:45:16,656][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.ModelCheckpoint>
[2023-08-05 07:45:16,658][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichModelSummary>
[2023-08-05 07:45:16,659][classifier.utils.instantiators][INFO] - Instantiating callback <lightning.pytorch.callbacks.RichProgressBar>
[2023-08-05 07:45:16,660][classifier.train][INFO] - Instantiating trainer <lightning.pytorch.trainer.Trainer>
[2023-08-05 07:45:16,740][pytorch_lightning.utilities.rank_zero][INFO] - Trainer already configured with model summary callbacks: [<class 'lightning.pytorch.callbacks.rich_model_summary.RichModelSummary'>]. Skipping setting a default `ModelSummary` callback.
[2023-08-05 07:45:16,763][pytorch_lightning.utilities.rank_zero][INFO] - GPU available: False, used: False
[2023-08-05 07:45:16,763][pytorch_lightning.utilities.rank_zero][INFO] - TPU available: False, using: 0 TPU cores
[2023-08-05 07:45:16,763][pytorch_lightning.utilities.rank_zero][INFO] - IPU available: False, using: 0 IPUs
[2023-08-05 07:45:16,764][pytorch_lightning.utilities.rank_zero][INFO] - HPU available: False, using: 0 HPUs
[2023-08-05 07:45:16,764][classifier.train][INFO] - Logging hyperparameters!
[2023-08-05 07:45:16,821][aim.sdk.reporter][INFO] - creating RunStatusReporter for bd5bdcbbd20f4b79aa6d010b
[2023-08-05 07:45:16,822][aim.sdk.reporter][INFO] - starting from: {}
[2023-08-05 07:45:16,822][aim.sdk.reporter][INFO] - starting writer thread for <aim.sdk.reporter.RunStatusReporter object at 0x7f48c2f94910>
[2023-08-05 07:45:17,037][classifier.train][INFO] - Starting training!
[2023-08-05 07:46:01,225][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 75, in train
    trainer.fit(model=model, datamodule=datamodule, ckpt_path=cfg.get("ckpt_path"))
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 529, in fit
    call._call_and_handle_interrupt(
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/call.py", line 42, in _call_and_handle_interrupt
    return trainer_fn(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 568, in _fit_impl
    self._run(model, ckpt_path=ckpt_path)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 973, in _run
    results = self._run_stage()
              ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/trainer/trainer.py", line 1016, in _run_stage
    self.fit_loop.run()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 201, in run
    self.advance()
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/fit_loop.py", line 354, in advance
    self.epoch_loop.run(self._data_fetcher)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 133, in run
    self.advance(data_fetcher)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/training_epoch_loop.py", line 189, in advance
    batch = next(data_fetcher)
            ^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 136, in __next__
    self._fetch_next_batch(self.dataloader_iter)
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loops/fetchers.py", line 150, in _fetch_next_batch
    batch = next(iterator)
            ^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 284, in __next__
    out = next(self._iterator)
          ^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/utilities/combined_loader.py", line 65, in __next__
    out[i] = next(self.iterators[i])
             ^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 633, in __next__
    data = self._next_data()
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/dataloader.py", line 677, in _next_data
    data = self._dataset_fetcher.fetch(index)  # may raise StopIteration
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torch/utils/data/_utils/fetch.py", line 51, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
            ~~~~~~~~~~~~^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 229, in __getitem__
    sample = self.loader(path)
             ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 268, in default_loader
    return pil_loader(path)
           ^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/torchvision/datasets/folder.py", line 247, in pil_loader
    img = Image.open(f)
          ^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='./data//PetImages_split/train/Dog/11702.jpg'>
[2023-08-05 07:46:01,237][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/logs/train/runs/2023-08-05_07-45-15
