[2023-07-21 20:09:34,722][classifier.train][INFO] - Instantiating datamodule <classifier.data.image_folder_datamodule.ImageFolderDataModule>
[2023-07-21 20:09:34,878][classifier.train][INFO] - Instantiating model <classifier.models.vit_module.VitLitModule>
[2023-07-21 20:09:34,965][classifier.train][INFO] - Instantiating loggers...
[2023-07-21 20:09:34,966][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.csv_logs.CSVLogger>
[2023-07-21 20:09:34,972][classifier.utils.instantiators][INFO] - Instantiating logger <aim.pytorch_lightning.AimLogger>
[2023-07-21 20:09:35,863][aim.utils.tracking][WARNING] - --------------------------------------------------------------------------
[2023-07-21 20:09:35,863][aim.utils.tracking][WARNING] -                  Aim collects anonymous usage analytics.                 
[2023-07-21 20:09:35,863][aim.utils.tracking][WARNING] -                         Read how to opt-out here:                         
[2023-07-21 20:09:35,864][aim.utils.tracking][WARNING] -     https://aimstack.readthedocs.io/en/latest/community/telemetry.html    
[2023-07-21 20:09:35,864][aim.utils.tracking][WARNING] - --------------------------------------------------------------------------
[2023-07-21 20:09:36,293][classifier.utils.instantiators][INFO] - Instantiating logger <lightning.pytorch.loggers.mlflow.MLFlowLogger>
[2023-07-21 20:09:36,296][classifier.utils.utils][ERROR] - 
Traceback (most recent call last):
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 92, in _call_target
    return _target_(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/lightning/pytorch/loggers/mlflow.py", line 151, in __init__
    raise ModuleNotFoundError(str(_MLFLOW_AVAILABLE))
ModuleNotFoundError: False

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/utils.py", line 65, in wrap
    metric_dict, object_dict = task_func(cfg=cfg)
                               ^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/train.py", line 49, in train
    logger: List[Logger] = utils.instantiate_loggers(cfg.get("logger"))
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/TSOA-Emlops-Deep-Learning-package/classifier/utils/instantiators.py", line 48, in instantiate_loggers
    logger.append(hydra.utils.instantiate(lg_conf))
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 226, in instantiate
    return instantiate_node(
           ^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 347, in instantiate_node
    return _call_target(_target_, partial, args, kwargs, full_key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspace/.pyenv_mirror/user/current/lib/python3.11/site-packages/hydra/_internal/instantiate/_instantiate2.py", line 97, in _call_target
    raise InstantiationException(msg) from e
hydra.errors.InstantiationException: Error in call to target 'lightning.pytorch.loggers.mlflow.MLFlowLogger':
ModuleNotFoundError('False')
full_key: logger.mlflow
[2023-07-21 20:09:36,301][classifier.utils.utils][INFO] - Output dir: /workspace/TSOA-Emlops-Deep-Learning-package/outputs/2023-07-21/20-09-34
